# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: news.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnews.proto\x12\x04news\"\r\n\x0bNewsRequest\"2\n\x0cNewsResponse\x12\"\n\nnews_items\x18\x01 \x03(\x0b\x32\x0e.news.NewsItem\"%\n\x08NewsItem\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t2A\n\x0bNewsService\x12\x32\n\tFetchNews\x12\x11.news.NewsRequest\x1a\x12.news.NewsResponseB\x19Z\x17path/to/your/proto;newsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'news_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027path/to/your/proto;news'
  _globals['_NEWSREQUEST']._serialized_start=20
  _globals['_NEWSREQUEST']._serialized_end=33
  _globals['_NEWSRESPONSE']._serialized_start=35
  _globals['_NEWSRESPONSE']._serialized_end=85
  _globals['_NEWSITEM']._serialized_start=87
  _globals['_NEWSITEM']._serialized_end=124
  _globals['_NEWSSERVICE']._serialized_start=126
  _globals['_NEWSSERVICE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
